services:
  postgres_db:
    image: postgres:16-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # Mount your local initialization script into the container's init folder
      - ./init-scripts:/docker-entrypoint-initdb.d
      # Named volume to persist data so you don't lose it when the container stops
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

#   stock_api:
#     container_name: stock_api
#     build:
#       context: .
#       dockerfile: /stock-api/Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production
#       - PORT=3000
#       - DATABASE_URL=postgresql://myuser:mysecretpassword@db:5432/production_db
#     depends_on:
#       postgres_db:
#         condition: service_healthy # Waits for the DB to be ready before starting the API
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

volumes:
  postgres_data: